baseURL: https://AnvayBuch.com
title: Anvay Buch
paginate: 6
theme: charlolamode
googleAnalytics: "UA-141527833-1"



menu:
    main:
        - name: About
          url: about/
          weight: 30
        - name: Blog
          url: blog/
          weight: 20
        # - name: Categories
        #   url: categories/
        #   weight: 10
        - name: Notes
          url: notes/
        #  weight: 10
        - name: Public Speaking
          url: publicspeaking/
        - name: Podcast
          url: podcast/
        - name: Uses
          url: uses/


params:
    author: Anvay Buch
    description: Hi, I am Anvay Buch, a Technical Support Engineer at UKG and Cloud & Security enthusiast.


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Anvay Buch 👋
        description: Ula
        imageUrl: "/images/profile.jpg"
        imageTitle: Anvay Buch
        imageWidth: 200
        imageHeight: 200
        buttons:
            - name: Portfolio
              url: https://www.youtube.com/@AnvayBuch7
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/asbuch99"
        - name: linkedin
          url: "https://www.linkedin.com/in/anvay-buch/"

    # change favicon in images folder (icon for web tab)
    #assets:
     #     favicon: "/images/favicon.ico"
      #    favicon16x16: "/images/favicon-16x16.png"
       #   favicon32x32: "/images/favicon-32x32.png"
        #  apple_touch_icon: "/images/apple-touch-icon.png"
         # safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

